spring.application.name=GGarciaProgramacionNCapasMavenService
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-parameters=10000
server.tomcat.max-part-count=10000
server.port=8081


